version: "3"
services:
  spa:
    build:
      context: ./spa
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3001" # Ánh xạ cổng 3001 của máy host tới cổng 3001 của container
  angular-app:
    build:
      context: ./angular-app
      dockerfile: .docker/Dockerfile
    ports:
      - "4200:4200" # Ánh xạ cổng 4200 của máy host tới cổng 4200 của container
  vue-app:
    build:
      context: ./vue-app
      dockerfile: .docker/Dockerfile
    ports:
      - "3002:3002" # Ánh xạ cổng 3002 của máy host tới cổng 3002 của container
